<?php

	/*
	* Hotfile.com module for the EasyOFSR class
	*
	* This class extends OFS_Object and contains the
	* code to login to, and get data from, hotfile.com
	*
	* @author		Robert McLeod
	* @copyright	Copyright 2009 Robert McLeod
	* @licence		GNU GPL
	* @version		0.1
	*/
	
	/* Class for hotfile.com */
	class OFS_hotfile.com extends OFS_Object {
	
		protected function processHTML() {
		
		}
	
	}
?>
